"""Generate on-device assets for the ESP32 sketch:
  - firmware/esp32_llm/vocab.h : token id -> raw UTF-8 bytes, so the device just
    Serial.write()s the bytes of each generated token (llama2.c style).
  - prints the prompt token ids for a fixed demo prompt to paste into the sketch.
"""

import argparse
import os

from tokenizers import Tokenizer

HERE = os.path.dirname(os.path.abspath(__file__))
TOK = os.path.join(HERE, "..", "data", "bpe32768.json")
OUT = os.path.join(HERE, "..", "firmware", "esp32_llm", "vocab.h")
PROMPT = "Once upon a time"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tok", default=TOK,
                    help="path to the BPE tokenizer JSON (default data/bpe32768.json)")
    args = ap.parse_args()
    tok = Tokenizer.from_file(args.tok)
    V = tok.get_vocab_size()

    # Raw bytes per token: decode single-id sequences. For the ASCII TinyStories
    # domain this reconstructs text exactly when pieces are concatenated.
    blob = bytearray()
    offs = [0]
    for i in range(V):
        s = tok.decode([i])
        blob.extend(s.encode("utf-8"))
        offs.append(len(blob))

    with open(OUT, "w") as f:
        f.write("// Generated by src/gen_assets.py -- token id -> raw UTF-8 bytes.\n")
        f.write("#ifndef VOCAB_H\n#define VOCAB_H\n")
        f.write(f"#define VOCAB_N {V}\n")
        f.write(f"static const unsigned char VOCAB_BLOB[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 20):
            f.write("  " + ",".join(str(b) for b in blob[i:i+20]) + ",\n")
        f.write("};\n")
        f.write(f"static const int VOCAB_OFF[{len(offs)}] = {{\n")
        for i in range(0, len(offs), 20):
            f.write("  " + ",".join(str(o) for o in offs[i:i+20]) + ",\n")
        f.write("};\n#endif\n")

    print(f"wrote {OUT}: {V} tokens, blob {len(blob)/1024:.0f} KB")

    ids = tok.encode(PROMPT).ids
    print(f'prompt "{PROMPT}" -> {len(ids)} ids: {ids}')
    print(f"round-trip: {tok.decode(ids)!r}")
    print("\nPaste into the sketch:")
    print(f"static const int PROMPT_IDS[] = {{{', '.join(map(str, ids))}}};")


if __name__ == "__main__":
    main()
